apiVersion: v1
kind: Secret
metadata:
  name: ez-book-secret
  namespace: ez-book
type: Opaque
stringData:
  GOOGLE_SHEETS_SPREADSHEET_ID: "<your-sheet-id>"
  GOOGLE_SHEETS_LOGS_SPREADSHEET_ID: "<your-logs-sheet-id>"
  GOOGLE_SHEETS_CLIENT_EMAIL: "<service-account-email>"
  GOOGLE_SHEETS_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
