apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ez-book-purchase-application.fullname" . }}-env
  labels:
    {{- include "ez-book-purchase-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOOGLE_SHEETS_SPREADSHEET_ID: {{ .Values.env.GOOGLE_SHEETS_SPREADSHEET_ID | quote }}
  GOOGLE_SHEETS_LOGS_SPREADSHEET_ID: {{ .Values.env.GOOGLE_SHEETS_LOGS_SPREADSHEET_ID | quote }}
  GOOGLE_SHEETS_CLIENT_EMAIL: {{ .Values.env.GOOGLE_SHEETS_CLIENT_EMAIL | quote }}
  GOOGLE_SHEETS_PRIVATE_KEY: {{ .Values.env.GOOGLE_SHEETS_PRIVATE_KEY | quote }}
