{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ez-book-purchase-application.secretName" . }}
  labels:
    {{- include "ez-book-purchase-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOOGLE_SHEETS_SPREADSHEET_ID: {{ .Values.secret.data.GOOGLE_SHEETS_SPREADSHEET_ID | quote }}
  GOOGLE_SHEETS_LOGS_SPREADSHEET_ID: {{ .Values.secret.data.GOOGLE_SHEETS_LOGS_SPREADSHEET_ID | quote }}
  GOOGLE_SHEETS_CLIENT_EMAIL: {{ .Values.secret.data.GOOGLE_SHEETS_CLIENT_EMAIL | quote }}
  GOOGLE_SHEETS_PRIVATE_KEY: {{ .Values.secret.data.GOOGLE_SHEETS_PRIVATE_KEY | quote }}
{{- end }}
