apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ez-book-purchase-application.fullname" . }}-env
  labels:
    {{- include "ez-book-purchase-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOOGLE_SHEETS_SPREADSHEET_ID: {{ .Values.GOOGLE_SHEETS_SPREADSHEET_ID | quote }}
  GOOGLE_SHEETS_LOGS_SPREADSHEET_ID: {{ .Values.GOOGLE_SHEETS_LOGS_SPREADSHEET_ID | quote }}
  GOOGLE_SHEETS_CLIENT_EMAIL: {{ .Values.GOOGLE_SHEETS_CLIENT_EMAIL | quote }}
  GOOGLE_SHEETS_PRIVATE_KEY: {{ .Values.GOOGLE_SHEETS_PRIVATE_KEY | quote }}

  SESSION_SECRET: {{ .Values.SESSION_SECRET | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.GOOGLE_OAUTH_CLIENT_ID | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.GOOGLE_OAUTH_CLIENT_SECRET | quote }}
  GOOGLE_OAUTH_REDIRECT_URI: {{ .Values.GOOGLE_OAUTH_REDIRECT_URI | quote }}
  ADMIN_EMAILS: {{ .Values.ADMIN_EMAILS | quote }}
